# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='mod',
            field=models.CharField(default='not_defined', max_length=30),
        ),
    ]
